<a href="https://colab.research.google.com/github/jilly4204/Github-and-Jupyter-setup/blob/main/Copy_of_api_and_webscraping_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# APIs

Application Programming Interfaces, or APIs, allow software to communicate with each other to exchange data and other functionality.

Most APIs are accessed using URL requests, much like requesting a page in a web browser. For our purposes, a URL is just a file or application that we can access using a web address (e.g., http://bc.edu). Python has features to help us make the requests.

The APIs we'll work with have URLs thst return data in raw formats such as `json` or `XML` files. These differ from the `html` files that we typically read in a web browswers. You learned about structured and unstructured data earlier. APIs return structured data; `html` files typically return unstructured data that is rendered for people to easily read.

### API example
We'll use GitHub a lot in our data science work, so let's use its API for our example. The GitHub API is accessible at `api.github.com.` This URL will return structured data files from Github.

In [ ]:
import pandas as pd

# The `requests` library allows us to make URL requests and retrieve data from
# URLs
import requests

Now we can make make a request to the GitHub API to return information about a specific user. That user should be you! Enter your GitHub name in the cell below and run it to make the API request.

In [ ]:
# request data from GitHub API about your account

# FILL IN YOUR GITHUB USER NAME BELOW
github_account_name = "jilly4204" # PUT YOUR GITHUB USER NAME BETWEEN THE QUOTES"

# DON'T CHANGE THE LINE BELOW!
assert github_account_name != "", f"Make sure to add your GitHub user name to the variable githib_account_name!"

# The GitHub API URL is https://api.github.com/users/YOUR_USER_NAME.
# Put your user name in the gihub_account_name variable named
# github_account_name. We use the '+' operator below to add
# the API URL with your user name

page = requests.get('https://api.github.com/users/' + github_account_name)

# the content we get back from `requests.get` is a json file
page.content

b'{"login":"jilly4204","id":325523541,"node_id":"U_kgDOE2cYVQ","avatar_url":"https://avatars.githubusercontent.com/u/325523541?v=4","gravatar_id":"","url":"https://api.github.com/users/jilly4204","html_url":"https://github.com/jilly4204","followers_url":"https://api.github.com/users/jilly4204/followers","following_url":"https://api.github.com/users/jilly4204/following{/other_user}","gists_url":"https://api.github.com/users/jilly4204/gists{/gist_id}","starred_url":"https://api.github.com/users/jilly4204/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jilly4204/subscriptions","organizations_url":"https://api.github.com/users/jilly4204/orgs","repos_url":"https://api.github.com/users/jilly4204/repos","events_url":"https://api.github.com/users/jilly4204/events{/privacy}","received_events_url":"https://api.github.com/users/jilly4204/received_events","type":"User","user_view_type":"public","site_admin":false,"name":null,"company":null,"blog":"","location":null,"email":null,"hireable":null,"bio":null,"twitter_username":null,"public_repos":1,"public_gists":0,"followers":0,"following":0,"created_at":"2026-09-06T06:32:08Z","updated_at":"2026-09-06T06:32:08Z"}'

JSON data is highly structured, but it's not always easy for people to read. We can make this easier by loading the data into a pandas dataframe. To do this, we call `page.json()` to return the data as a Python dictionary. We can make the dataframe from that dictionary using `from_dict`.

In [ ]:
# use the argument orient=index in the call to from_dict. Why?
# this tells pandas that the keys of the dictionary are row
# indices, and the values are the row data
df = pd.DataFrame.from_dict(page.json(), orient='index')
df

                                                                     0
login                                                        jilly4204
id                                                           325523541
node_id                                                   U_kgDOE2cYVQ
avatar_url           https://avatars.githubusercontent.com/u/325523...
gravatar_id
url                             https://api.github.com/users/jilly4204
html_url                                  https://github.com/jilly4204
followers_url         https://api.github.com/users/jilly4204/followers
following_url        https://api.github.com/users/jilly4204/followi...
gists_url            https://api.github.com/users/jilly4204/gists{/...
starred_url          https://api.github.com/users/jilly4204/starred...
subscriptions_url    https://api.github.com/users/jilly4204/subscri...
organizations_url          https://api.github.com/users/jilly4204/orgs
repos_url                 https://api.github.com/users/jilly4204/repos
events_url           https://api.github.com/users/jilly4204/events{...
received_events_url  https://api.github.com/users/jilly4204/receive...
type                                                              User
user_view_type                                                  public
site_admin                                                       False
name                                                              None
company                                                           None
blog
location                                                          None
email                                                             None
hireable                                                          None
bio                                                               None
twitter_username                                                  None
public_repos                                                         1
public_gists                                                         0
followers                                                            0
following                                                            0
created_at                                        2026-09-06T06:32:08Z
updated_at                                        2026-09-06T06:32:08Z

APIs let us collect structured data with a few Python commands. In this case, you just pulled data about your GitHub profile. This might be useful if we were asking questions about GitHub usages amongst a group of people. We could use the GitHub API to collect structured data on each individual then combine the information for deeper analyses. An important thing to note is that getting data from APIs is generally much easier than doing web scraping.

# Web Scraping

<div class="alert alert-info">
Web scrapers are programs that read and extract data from websites.
</div>

The websites generally consist of text and HTML tags. Those tags define the structure and layout of the document. For instance, we see tags like `<i>` to italicize text, tags like `<table>` to define tables of data. We're going to extract a table from a Wikipedia page in this example.  

For general web scraping, the Python library called [BeautifulSoup](https://beautiful-soup-4.readthedocs.io/en/latest/) is an incredibly useful tool. But pandas has a convenient function named `read_html`. It does just that: Read HTML files so they can be worked with as dataframes.  

We'll use the Python library called `requests` again to  retrieve web site content. Let's import it and `pandas`.

In [ ]:
# requests is a library that lets us read from web pages.
import requests

# StringIO is a library that lets us treat strings as if they're files. Functions like `read_html()` want strings
# to be StringIO objects if they're not reading from actual files. You'll see an example below.
from io import StringIO

# This one should look familiar...
import pandas as pd

### Getting the Web Content
The first thing to do is to grab the contents of our website.   

Make a variable called `skycrapercenter_url` that holds the link to the tallest buildings page on Wikipedia. That URL is:  
[https://www.skyscrapercenter.com/buildings](https://www.skyscrapercenter.com/buildings)  

Use `requests.get()` to open the URL using `skycrapercenter_url` as its input. That will give you the webpage: Store this in a variable named `skyscraper_page`.

In [ ]:
# site_url will hold the URL for the Wikipedia building page
skycrapercenter_url = "https://www.skyscrapercenter.com/buildings"

# get the web page using the URL request
skyscraper_page = requests.get(skycrapercenter_url)

`requests.get()` returns a `Response` object that has a few useful methods associated with it. `.text` is one of them.

Let's print the first 1000 characters of the skyscrapercenter.com entry. We do that by requesting the `.text` of `skyscraper_page`.

In [ ]:
# print the first 1000 characters of the web page
print(skyscraper_page.text[0:1000])

<!doctype html>
<html>
<head>
    <title>
                    The 100 Tallest Completed Buildings in the World in 2026 -
                The Skyscraper Center
    </title>

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="/css/app.css?id=1ad9a1093fe2fc6378ab87fc3598ea84" rel="stylesheet">
    <link href="/css/header.css" rel="stylesheet">
    <link href="/css/leaflet.css" rel="stylesheet">
    <link href="/ammap/ammap.css" rel="stylesheet">
    <link href="/css/jquery.dataTables.css" rel="stylesheet">

    <link href="//cdn.jsdelivr.net/qtip2/2.2.1/jquery.qtip.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.13.1/css/all.css"/>

    <link href="/css/redesign.css" rel="stylesheet">

        <link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/fixedhead

This is definitely HTML and not meant for human consumption. How can we find the table(s) on the page?  

`read_html` is designed to specifically look for the tables. Let's use it on the skyscraper_page text.

In [ ]:
# Find tables on the web page using read_html
# The skyscraper_page.text is wrapped in a StringIO type. This
# is an object for reading and writing files
skyscraper_tables = pd.read_html(StringIO(skyscraper_page.text))

# let's see what we get in skyscraper_tables
print("skyscraper_tables is a", type(skyscraper_tables), "of length", len(skyscraper_tables))

skyscraper_tables is a <class 'list'> of length 1

Before looking at the skyscraper_tables content, we checked its type to see that it's a list with 1 element. The length is 1 because there's only 1 table on the page. If we're lucky, that first/only item in the list is the table of skyscraper heights. Let's take a look.

In [ ]:
skyscraper_data = skyscraper_tables[0]
skyscraper_data.head()

,Rank,Name,City,Status Completed Architecturally Topped Out Structurally Topped Out Under Construction On Hold Proposed Vision Never Completed Demolished Competition Entry Canceled Proposed Renovation Under Renovation Renovated Under Demolition See all status definitions,"Completion A Completed building must fulfill all the following criteria: Topped out structurally and architecturally Fully clad Open for business, or at least partially occupiable","Height The level of the lowest, significant, open-air, pedestrian entrance to the architectural top of the building, including spires, but not including antennae, signage, flagpoles or other functional-technical equipment.","Floors Includes all above-ground floors, including the ground floor itself, and significant mezzanine floors / major mechanical plant floors, unless they have a significantly smaller floor area than the major floors below. Mechanical penthouses or plant rooms above the general roof area are not counted.","Material All-Steel Both the main vertical/lateral structural elements and the floor spanning systems are constructed from steel. Note that a building of steel construction with a floor system of concrete planks or concrete slab on top of steel beams is still considered an “all-steel” structure as the concrete elements are not acting as the primary structure. All-Concrete Both the main vertical/lateral structural elements and the floor spanning systems are constructed from concrete which has been cast in place and utilizes steel reinforcement bars and/or steel reinforced concrete which has been precast as individual components and assembled together on-site. All-Timber Both the main vertical/lateral structural elements and the floor spanning systems are constructed from timber. An all-timber structure may include the use of localized non-timber connections between timber elements. Note that a building of timber construction with a floor system of concrete planks or concrete slab on top of timber beams is still considered an “all-timber” structure as the concrete elements are not acting as the primary structure. Mixed-Structure Utilizes distinct systems (e.g. all-steel, all-concrete, all-timber), one on top of the other. For example, a Steel Over Concrete indicates an all-steel structural system located on top of an all-concrete structural system, with the opposite true of Concrete Over Steel. Composite A combination of materials (e.g. steel, concrete, timber) are used together in the main structural elements. Examples include buildings which utilize: steel columns with a floor system of reinforced concrete beams; a steel frame system with a concrete core; concrete-encased steel columns; concrete-filled steel tubes; etc. Where known, the CVU database breaks out the materials used within a composite building’s primary structural elements.","Function A single-function tall building is defined as one where 85 percent or more of its total height is dedicated to a single function. A mixed-use tall building contains two or more functions, where each of the functions occupies a significant proportion of the tower’s total space. Support areas, such as car parks and mechanical plant space, do not constitute mixed-use functions. Functions are denoted on CVU “Tallest” lists in descending order (e.g., “hotel/office” indicates hotel function above office function)."
0,1,Burj Khalifa,Dubai,NaN,2010,"828 m / 2,717 ft",163,Steel Over Concrete,Office / Residential / Hotel
1,2,Menara Merdeka Maybank,Kuala Lumpur,NaN,2023,"679 m / 2,227 ft",118,Concrete-Steel Composite,Hotel / Serviced Apartments / Office
2,3,Shanghai Tower,Shanghai,NaN,2015,"632 m / 2,073 ft",128,Concrete-Steel Composite,Hotel / Office
3,4,Makkah Royal Clock Tower,Mecca,NaN,2012,"601 m / 1,972 ft",120,Steel Over Concrete,Serviced Apartments / Hotel / Retail
4,5,Ping An Finance Center,Shenzhen,NaN,2017,"599 m / 1,965 ft",115,Concrete-Steel Composite,Office

### Cleaning the columns
That looks like the table we saw at [https://www.skyscrapercenter.com/buildings](https://www.skyscrapercenter.com/buildings). Except the headings are ridiculously long. `read_html` extracted the header names **and** additional infomation text buried in the headers (you'll see the text by rolling over the ⓘ symbol in the header row). We just want the column titles, so let's clean up the dataframe.

In [ ]:
# make a list with new column names
columns = ['rank', 'name', 'city', 'status', 'completion', 'height', 'floors', 'material', 'function']

skyscraper_data = skyscraper_tables[0]

# set the columns to the columns list
skyscraper_data.columns = columns

# see if it worked
skyscraper_data.head()

,rank,name,city,status,completion,height,floors,material,function
0,1,Burj Khalifa,Dubai,NaN,2010,"828 m / 2,717 ft",163,Steel Over Concrete,Office / Residential / Hotel
1,2,Menara Merdeka Maybank,Kuala Lumpur,NaN,2023,"679 m / 2,227 ft",118,Concrete-Steel Composite,Hotel / Serviced Apartments / Office
2,3,Shanghai Tower,Shanghai,NaN,2015,"632 m / 2,073 ft",128,Concrete-Steel Composite,Hotel / Office
3,4,Makkah Royal Clock Tower,Mecca,NaN,2012,"601 m / 1,972 ft",120,Steel Over Concrete,Serviced Apartments / Hotel / Retail
4,5,Ping An Finance Center,Shenzhen,NaN,2017,"599 m / 1,965 ft",115,Concrete-Steel Composite,Office

And there you have it, a Pandas dataframe with all of the data from the skyscraper webpage! That was a lot of work, so let's save the dataframe so we don't need to scrape the web page again. We use `to_csv` to convert the dataframe into a CSV file. We also add the argument `index=False`; this will drop the index values (0,1,2...) from the CSV file. They'll return when we reload the file into a dataframe.

In [ ]:
skyscraper_data.to_csv("tallest_skyscrapers.csv", index=False)